version: "3.9"
services:
  frontend:
    image: sermalenk/skypro-front:lesson-37
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    image: usefulsan/todolist:$GITHUB_RUN_ID
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition:
          service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/django/.env

  migrations:
    image: usefulsan/todolist:$GITHUB_RUN_ID
    command: bash -c "python manage.py migrate"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/django/.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./db/postgres:/var/lib/postgresql/data