version: "3.9"
services:
  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      - api

  api:
    build:
      context: .
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition:
          service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/django/.env

  migrations:
    build:
      context: .
    command: bash -c "python manage.py migrate"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.env:/django/.env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todolist
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  bot:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.env:/django/.env
    command: python manage.py runbot

