name: Build and deploy action

on:
  push:
    branches: [ "master" ]

env:
  version: $GITHUB_RUN_ID
  user: ${{ secrets.DOCKERHUB_USERNAME }}

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build -t ${{ env.user }}/todolist:${{ env.version }} .
    
    - name: Docker login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ env.user }}
        password: ${{ secrets.DOCKER_HUB_TOKEN_FOR_YANDEX_VM }}
          
    - name: Push the Docker image
      run: docker push ${{ env.user }}/todolist:${{ env.version }}
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
    - name: clone code
      uses: actions/checkout@v3

    - name: render configs
      run: |
        mkdir deploy
        cat docker-compose-ci.yaml | envsubst > deploy/docker-compose.yaml
        cat docker_ci_config.py | envsubst > deploy/docker_config.py 
    - name: clone files to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_LOGIN }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "deploy/docker-compose.yaml,deploy/docker_config.py"
        target: "django"
        strip_components: 1
    - name: run docker-compose
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_LOGIN }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          cd django
          echo ${{ secrets.SSH_PASSWORD }} | sudo -S docker-compose up -d